name: Build and run tests
on:
  push: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Build and run tests
    steps:
    - uses: actions/checkout@master
    - name: Select latest Xcode
      run: sudo xcode-select --switch /Applications/Xcode_12_beta.app/Contents/Developer/
    - name: Install tools
      run: |
        brew install llvm wabt
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        cd $(mktemp -d)
        wget https://github.com/cranestation/wasmtime/releases/download/dev/wasmtime-dev-x86_64-macos.tar.xz
        tar xfz wasmtime-dev-x86_64-macos.tar.xz
        sudo cp wasmtime-dev-x86_64-macos/wasmtime /usr/local/bin/wasmtime
    - name: Download Toolchain
      run: |
        VERSION=swift-wasm-5.3.1-RELEASE
        TOOLCHAIN_URL="https://github.com/swiftwasm/swift/releases/download/$VERSION/$VERSION-macos_x86_64.pkg"
        wget $TOOLCHAIN_URL
        installer -target CurrentUserHomeDirectory -pkg $VERSION-macos_x86_64.pkg
        echo "SWIFT_TOOLCHAIN=$HOME/Library/Developer/Toolchains/$VERSION.xctoolchain/usr/" >> $GITHUB_ENV
    - name: Build Fixtures
      run: |
        cd Fixtures
        make all
    - name: Build
      run: swift build
    - name: Test
      run: swift test
